name: "Org Project Metrics"
description: "Collect GitHub Projects v2 stats and inject metrics into README"

inputs:
  org:
    description: "GitHub organization name"
    required: true
  token:
    description: "GitHub token with projects access"
    required: true
  readme_path:
    description: "Path to the README file"
    default: "profile/README.md"
  template_path:
    description: "Path to the README template (default: sample-README.md in action)"
    default: "sample-README.md"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install jq
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Collect project data
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/scripts/get_data.sh"
        "$GITHUB_ACTION_PATH/scripts/get_data.sh" "${{ inputs.org }}" "$GITHUB_WORKSPACE/data/projects.json"

    - name: Generate README
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/scripts/update_readme.sh"
        
        if [[ "${{ inputs.template_path }}" == "sample-README.md" ]]; then
          TEMPLATE="$GITHUB_ACTION_PATH/sample-README.md"
        else
          TEMPLATE="$GITHUB_WORKSPACE/${{ inputs.template_path }}"
        fi
        
        "$GITHUB_ACTION_PATH/scripts/update_readme.sh" \
          "$GITHUB_WORKSPACE/data/projects.json" \
          "$TEMPLATE" \
          "$GITHUB_WORKSPACE/${{ inputs.readme_path }}"
