name: "Org Project Metrics"
description: "Collect GitHub Projects v2 stats and inject a metrics table into a README"

inputs:
  org:
    description: "GitHub organization name"
    required: true
  token:
    description: "GitHub token with projects access"
    required: true
  readme_path:
    description: "Path to the README file"
    default: "profile/README.md"

runs:
  using: "composite"
  steps:
    - name: Collect project stats
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/scripts/"*.sh
        "$GITHUB_ACTION_PATH/scripts/collect-stats.sh" "${{ inputs.org }}"

    - name: Build metrics display
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/scripts/build-global-overview.sh"
        "$GITHUB_ACTION_PATH/scripts/build-project-breakdown.sh"
        "$GITHUB_ACTION_PATH/scripts/build-languages.sh"
        "$GITHUB_ACTION_PATH/scripts/build-last-updated.sh"

    - name: Inject sections into README
      shell: bash
      run: |
        mkdir -p "$(dirname \"${{ inputs.readme_path }}\")"
        
        # Check required temp files exist
        for file in "global-overview.tmp" "project-breakdown.tmp" "languages.tmp" "last-updated.tmp"; do
          if [[ ! -f "$file" ]]; then
            echo "ERROR: $file not found. Build scripts may have failed."
            exit 1
          fi
        done
        
        if [[ ! -f "${{ inputs.readme_path }}" ]]; then
          echo "ERROR: README file not found at ${{ inputs.readme_path }}"
          exit 1
        fi
        
        # Inject all sections
        awk -f "$GITHUB_ACTION_PATH/scripts/inject-global-overview.awk" "${{ inputs.readme_path }}" > "${{ inputs.readme_path }}.tmp" && \
        awk -f "$GITHUB_ACTION_PATH/scripts/inject-project-breakdown.awk" "${{ inputs.readme_path }}.tmp" > "${{ inputs.readme_path }}.new" && \
        awk -f "$GITHUB_ACTION_PATH/scripts/inject-languages.awk" "${{ inputs.readme_path }}.new" > "${{ inputs.readme_path }}.tmp" && \
        awk -f "$GITHUB_ACTION_PATH/scripts/inject-last-updated.awk" "${{ inputs.readme_path }}.tmp" > "${{ inputs.readme_path }}.new"
        
        mv "${{ inputs.readme_path }}.new" "${{ inputs.readme_path }}"
