name: "Org Project Metrics"
description: "Collect GitHub Projects v2 stats and inject a metrics table into a README"

inputs:
  org:
    description: "GitHub organization name"
    required: true
  token:
    description: "GitHub token with projects access"
    required: true
  readme_path:
    description: "Path to the README file"
    default: ".github/profile/README.md"

runs:
  using: "composite"
  steps:
    - name: Collect project stats
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/scripts/"*.sh
        "$GITHUB_ACTION_PATH/scripts/collect-stats.sh" "${{ inputs.org }}"

    - name: Build metrics table
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/scripts/build-table.sh"

    - name: Inject table into README
      shell: bash
      run: |
        mkdir -p "$(dirname \"${{ inputs.readme_path }}\")"
        if [[ ! -f "table.tmp" ]]; then
          echo "ERROR: table.tmp not found. Make sure build-table.sh ran successfully."
          exit 1
        fi
        if [[ ! -f "${{ inputs.readme_path }}" ]]; then
          echo "ERROR: README file not found at ${{ inputs.readme_path }}"
          exit 1
        fi
        if ! grep -q "<!-- METRICS:START -->" "${{ inputs.readme_path }}" || ! grep -q "<!-- METRICS:END -->" "${{ inputs.readme_path }}"; then
          echo "ERROR: README file missing METRICS markers"
          exit 1
        fi
        awk -f "$GITHUB_ACTION_PATH/scripts/inject-readme.awk" "${{ inputs.readme_path }}" > "${{ inputs.readme_path }}.new"
        mv "${{ inputs.readme_path }}.new" "${{ inputs.readme_path }}"
